baseURL: https://xiang0805.github.io/
languageCode: 
  - en-us
  - zh-TW
title: 強人所男的實驗室
theme: "PaperMod"
paginate: 6



params:
  env: production
  googleAnalytics: "G-XSDK72PYV4"
  busuanzi:
        enable: true
  homeInfoParams:
    Title: 哈囉,我是王冠翔 
    Content: >
      - 目前是Workinlab健身工作室的策略長&體能教練，也有在長照中心指導樂齡班。    
      - 喜歡閱讀、運動、走訪大自然。
      - 使命-透過運動改善關節疼痛!
  socialIcons: # optional
    - name: "facebook"
      url: "https://www.facebook.com/profile.php?id=100000716446411"
    - name: "instagram"
      url: "https://www.instagram.com/guansiang_wang/"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/guansiang-wang"
    - name: "email"
      url: "mailto:guansiang.wang@gmail.com"
  
  profileMode:
        enabled: false
        title: "強人所男的實驗室" # optional default will be site title
        subtitle: "透過運動改善關節疼痛!"
        #imageUrl: "https://cdn.jsdelivr.net/gh/xiang0805/blogimage@main/img/自我介紹.jpeg" # optional
        #imageTitle: "<title of image as alt>" # optional
        #imageWidth: 120 # custom size
        #imageHeight: 120 # custom size
        #buttons:
         #   - name: Archive
          #    url: "/archive"
           # - name: Github
            #  url: "https://github.com/"  
  sitemap:
    changefreq: monthly
    filename: sitemap.xml
    priority: 0.5
  ShowShareButtons: false
  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  author: "王冠翔"
  contact: "forcemanlab@gmail.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

  

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: 分類
      url: /categories/
      weight: 10
    - identifier: tags
      name: 關鍵字
      url: /tags/
      weight: 20
    - identifier: search
      name: 搜尋
      url: /search/
      weight: 20
    - identifier: archive
      name: 每月精選
      url: /archives/
      weight: 20
