baseURL: https://xiang0805.github.io/
languageCode: 
  - en-us
  - zh-TW
title: 強人所男的實驗室
theme: "PaperMod"
paginate: 6
params:
  homeInfoParams:
    Title: 哈囉,我是王冠翔 wave
    Content: 目前是Workinlab健身工作室的策略長&體能教練，也有在長照中心指導樂齡班。 喜歡烹飪、閱讀、運動、走訪大自然。
  socialIcons: # optional
    - name: "facebook"
      url: "https://www.facebook.com/profile.php?id=100000716446411"
    - name: "instagram"
      url: "https://www.instagram.com/guansiang_wang/"
  profileMode:
        enabled: false
        title: "強人所男的實驗室" # optional default will be site title
        subtitle: "透過運動改善關節疼痛!"
        imageUrl: "https://cdn.jsdelivr.net/gh/xiang0805/blogimage@main/img/自我介紹.jpeg" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Archive
              url: "/archive"
            - name: Github
              url: "https://github.com/"  
  
  ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  author: "王冠翔"
  contact: "forcemanlab@gmail.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
